name: Check Secret

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    environment: dev-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x check.sh

      - name: Run check script
        run: ./check.sh "${{ secrets.supersecret }}"

  check-dev-2:
    runs-on: ubuntu-latest
    environment: dev-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x check.sh

      - name: Run check script
        run: ./check.sh "${{ secrets.supersecret }}"
